<a href="https://colab.research.google.com/github/ohsung252/toan-roi-rac/blob/main/toan_roi_rac_buoi_8_ohsung.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.3 Cây khung và cây khung tối thiểu 

In [3]:
import networkx as nx
g = nx.Graph()
g.add_node('TP.HCM')
g.add_node('Dong Nai')
g.add_node('Ba Ria Vung Tau')
g.add_node('Lam Dong')
g.add_node('Can Tho')
g.add_node('Long An')
g.add_node('Tien Giang')
g.add_edge('TP.HCM', 'Dong Nai', weight = 50)
g.add_edge('TP.HCM', 'Ba Ria Vung Tau', weight = 120)
g.add_edge('TP.HCM', 'Long An', weight = 40)
g.add_edge('Dong Nai', 'Lam Dong', weight = 230)
g.add_edge('Dong Nai', 'Ba Ria Vung Tau', weight = 60)
g.add_edge('Tien Giang', '29') # lệnh gõ nhầm
g.remove_edge('Tien Giang', '29') # xóa lệnh gõ nhầm
g.add_edge('Tien Giang', 'Long An') #lệnh gõ thiếu chiều dài (trọng số, weight)
g.remove_edge('Tien Giang', 'Long An') # xóa lệnh gõ thiếu chiều dài
g.add_edge('Tien Giang', 'Long An', weight = 29)
g.add_edge('Tien Giang', 'Can Tho', weight = 200)
g.add_edge('Long An', 'Dong Nai', weight = 70)
g.nodes()


NodeView(('TP.HCM', 'Dong Nai', 'Ba Ria Vung Tau', 'Lam Dong', 'Can Tho', 'Long An', 'Tien Giang', '29'))

In [4]:
g.remove_node('29')
g.nodes()

NodeView(('TP.HCM', 'Dong Nai', 'Ba Ria Vung Tau', 'Lam Dong', 'Can Tho', 'Long An', 'Tien Giang'))

In [5]:
sorted(g.edges(data=True))

[('Can Tho', 'Tien Giang', {'weight': 200}),
 ('Dong Nai', 'Ba Ria Vung Tau', {'weight': 60}),
 ('Dong Nai', 'Lam Dong', {'weight': 230}),
 ('Dong Nai', 'Long An', {'weight': 70}),
 ('Long An', 'Tien Giang', {'weight': 29}),
 ('TP.HCM', 'Ba Ria Vung Tau', {'weight': 120}),
 ('TP.HCM', 'Dong Nai', {'weight': 50}),
 ('TP.HCM', 'Long An', {'weight': 40})]

In [6]:
T = nx.maximum_spanning_tree(g) 
sorted(T.edges(data=True)) 

[('Can Tho', 'Tien Giang', {'weight': 200}),
 ('Dong Nai', 'Ba Ria Vung Tau', {'weight': 60}),
 ('Dong Nai', 'Lam Dong', {'weight': 230}),
 ('Dong Nai', 'Long An', {'weight': 70}),
 ('Long An', 'Tien Giang', {'weight': 29}),
 ('TP.HCM', 'Ba Ria Vung Tau', {'weight': 120})]

In [7]:
T.nodes()

NodeView(('TP.HCM', 'Dong Nai', 'Ba Ria Vung Tau', 'Lam Dong', 'Can Tho', 'Long An', 'Tien Giang'))

#2.0 Một số tham khảo về hỗ trợ của gói Networkx để xử lý mạng đồ thị và cây: 

Phân tích Pagerank (chỉ số kết nối):

In [8]:
nx.pagerank(g, 0.85)

{'Ba Ria Vung Tau': 0.11598739208998517,
 'Can Tho': 0.13462563996889282,
 'Dong Nai': 0.23515074008532225,
 'Lam Dong': 0.13355497428234894,
 'Long An': 0.09373705822226845,
 'TP.HCM': 0.1344588073814972,
 'Tien Giang': 0.15248538796968536}

Lệnh sau để phân các vùng gần nhau: 

In [9]:
nx.min_edge_cover(g) 

{('Lam Dong', 'Dong Nai'),
 ('Long An', 'TP.HCM'),
 ('TP.HCM', 'Ba Ria Vung Tau'),
 ('TP.HCM', 'Long An'),
 ('Tien Giang', 'Can Tho')}

#3.3. [Đọc thêm] Cài đặt thuật toán D8

In [10]:
import math
import numpy as np
def tinh_huong(dem, m_dong, n_cot, vitri):
 huong = np.zeros((m_dong, n_cot))
 for dong in range(m_dong):
  for cot in range(n_cot):
    xx, yy, mymax = 0, 0, 0
    for i in range(-1,2):
      for j in range(-1,2):
        if (i*i+j*j>0) and \
          (dong+i>=0) and (dong+i<m_dong) and \
          (cot+j>=0) and (cot+j<n_cot) and \
          (mymax*math.sqrt(i*i+j*j) < dem[dong][cot] - dem[dong+i][cot+j]):
            mymax = dem[dong][cot] - dem[dong+i][cot+j] 
            xx = i 
            yy = j
    huong[dong][cot] = vitri[xx+1][yy+1]
 return huong

In [13]:
def tinh_tichluy(p, q, m_dong, n_cot):
  for i in range(-1, 2):
    for j in range(-1,2):
      if (i*i+j*j>0) and \
        (p+i>=0) and (p+i<m_dong) and \
        (q+j>=0) and (q+j<n_cot) and \
        (huong[p+i][q+j] == vitri[-(i-1)][-(j-1)]):
          t1.append(1)
          tinh_tichluy(p+i, q+j, m_dong, n_cot)
  return len(t1)
vitri = np.array([ [32,64,128],[16,0,1],[8,4,2]])
#dem = [ [0 for j in range(n_cot)] for i in range(m_dong)]
# Giả định dữ liệu địa hình dem là một bảng 6x6 dưới đây:
dem = np.array([[78,72,69,71,58,49],
                [74,67,56,49,46,50],
                [69,53,44,37,38,48],
                [64,58,55,22,31,24],
                [68,61,47,21,16,19],
                [74,53,34,12,11,12]]) 

In [14]:
m_dong = dem.shape[0] #6
n_cot = dem.shape[1] #6
tichluy = np.zeros((m_dong, n_cot)) #[ [0 for j in range(n_cot)] for i in range(m_dong)]
huong = tinh_huong(dem, 6,6, vitri)
for i in range(m_dong):
 for j in range(n_cot):
  t1 = []
  tichluy[i][j] = tinh_tichluy(i, j, m_dong, n_cot) 

In [15]:
print (dem)

[[78 72 69 71 58 49]
 [74 67 56 49 46 50]
 [69 53 44 37 38 48]
 [64 58 55 22 31 24]
 [68 61 47 21 16 19]
 [74 53 34 12 11 12]]


In [16]:
print (huong) 

[[  2.   2.   2.   4.   4.   8.]
 [  2.   2.   2.   4.   8.   8.]
 [  1.   1.   2.   4.   8.   4.]
 [128. 128.   1.   2.   4.   8.]
 [  2.   2.   1.   4.   4.   8.]
 [  1.   1.   1.   1.   0.  16.]]


In [17]:
print (tichluy) 

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  2.  2.  0.]
 [ 0.  3.  7.  8.  1.  0.]
 [ 0.  0.  0. 20.  0.  1.]
 [ 0.  0.  0.  1. 24.  0.]
 [ 0.  2.  4.  7. 35.  0.]]
